services:
  - type: web
    name: dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard.py

  - type: worker
    name: bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py